# Stage 1: Build the Angular app
FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install

# COPY . /app/

# RUN npm run build 
# RUN npm run build --prod --output-path=./dist/capirelaterra
# CMD ["ng", "serve"]

EXPOSE 4200

# CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--port", "4200"]


# Stage 2: Serve the app with Nginx
# FROM nginx:alpine
# COPY --from=build /app/dist/capirelaterra /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]
