FROM node:latest

WORKDIR /app

COPY ./package*.json ./

RUN apt-get update && apt-get install
RUN npm install
RUN npm init playwright@latest
RUN npx playwright install

# COPY . /app/

# RUN npm run build

EXPOSE 3000

# CMD ["npm", "start"]
CMD ["npx", "ts-node", "--files","src/server.ts"]
# npx ts-node src/server.ts
